resolver: ghc-8.0.2

packages:
  - .

nix:
  enable: true
  shell-file: shell.nix

# extra-deps:
#   - X11-1.8
#   - X11-xft-0.3.1
#   - directory-1.2.7.1
#   - xmobar-0.24.3
#   - xmonad-0.13
#   - xmonad-contrib-0.13
